---
title: Better BibTeX
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
markdown: kramdown
redcarpet:
  extensions:
  - with_toc_data
kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: "/:categories/:title"
description: Making Zotero all it can be for us LaTeX holdouts
baseurl: zotero-better-bibtex
author:
  name: Mark Otto
  url: https://twitter.com/mdo
paginate: 5
github:
  repo: https://github.com/ZotPlus/zotero-better-bibtex/
  release: https://github.com/ZotPlus/zotero-better-bibtex/releases/latest
travis:
  build: https://travis-ci.org/ZotPlus/zotero-better-bibtex
  status: https://travis-ci.org/ZotPlus/zotero-better-bibtex.svg?branch=master
gems:
- jekyll-redirect-from
